import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  profilePictureContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  profilePictureWrapper: {
    position: 'relative',
    alignItems: 'center',
  },
  profilePictureButton: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FB7A20',
    borderStyle: 'dashed',
    marginBottom: 12,
  },
  profilePicture: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  profilePicturePlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilePictureText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 12,
    textAlign: 'center',
  },
  profilePictureSubtext: {
    color: '#666',
    fontSize: 14,
    marginTop: 4,
    textAlign: 'center',
  },
  cameraIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFF5F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  photoOptionalText: {
    color: '#999',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 16,
    fontStyle: 'italic',
  },
  removePictureButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  removePictureText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
    width: '100%',
  },
  secondaryButton: {
    backgroundColor: 'white',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: '#FB7A20',
    alignItems: 'center',
    width: 100,
    marginRight: 6,
  },
  secondaryButtonText: {
    color: '#FB7A20',
    fontSize: 16,
    fontWeight: 'bold',
  },
  accountTypeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#e9ecef',
    marginBottom: 16,
    width: '100%',
  },
  accountTypeContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  accountTypeText: {
    marginLeft: 16,
    flex: 1,
  },
  cuisineContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
    justifyContent: 'center',
  },
  cuisineTag: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  cuisineTagSelected: {
    backgroundColor: '#FB7A20',
    borderColor: '#FB7A20',
  },
  cuisineTagText: {
    color: '#666',
    fontSize: 14,
  },
  cuisineTagTextSelected: {
    color: '#FFFFFF',
  },
  skipPhotoButton: {
    marginTop: 16,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  skipPhotoText: {
    color: '#666',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  photoOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 16,
    width: '100%',
  },
  fallbackPhotoButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  fallbackPhotoText: {
    color: '#FB7A20',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  addressSuggestionsContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#eee',
    marginTop: 8,
    maxHeight: 300, // Increased from 200 to 300 to show more suggestions
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  addressSuggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    minHeight: 48,
  },
  addressSuggestionText: {
    color: '#222',
    fontSize: 14,
    flex: 1,
    lineHeight: 18,
  },
  urlPhotoButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  urlPhotoText: {
    color: '#666',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  urlInputContainer: {
    marginTop: 16,
    width: '100%',
  },
  urlInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    fontFamily: 'Figtree_400Regular',
    marginBottom: 8,
  },
  urlSubmitButton: {
    backgroundColor: '#FB7A20',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  urlSubmitText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Figtree_400Regular',
  },
  seeMoreButton: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#FB7A20',
    borderRadius: 12,
    alignItems: 'center',
  },
  seeMoreButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Figtree_400Regular',
  },
  validationContainer: {
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  validationStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  validationText: {
    fontSize: 14,
    fontFamily: 'Figtree_400Regular',
  },
  validationError: {
    color: '#ff4444',
  },
  validationSuccess: {
    color: '#4CAF50',
  },
  // Operating Hours Styles
  hoursDayContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#eee',
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  hoursDayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  hoursDayText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
    fontFamily: 'Figtree_600SemiBold',
  },
  hoursSlotsContainer: {
    gap: 12,
  },
  hoursSlotRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  timeInputContainer: {
    flex: 1,
  },
  timeLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
    fontFamily: 'Figtree_400Regular',
  },
  timeInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 8,
    fontSize: 14,
    fontFamily: 'Figtree_400Regular',
    textAlign: 'center',
    backgroundColor: '#f9f9f9',
  },
  removeSlotButton: {
    padding: 4,
  },
  addSlotButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f0f8ff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0f0ff',
    marginTop: 8,
  },
  addSlotText: {
    color: '#FB7A20',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
    fontFamily: 'Figtree_500Medium',
  },
  // Fixed Header Styles for Hours Step
  hoursHeaderContainer: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    zIndex: 1,
  },
  hoursTitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 8,
    textAlign: 'center',
    lineHeight: 22,
    fontFamily: 'Figtree_600SemiBold',
  },
  hoursSubtitle: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: 'Figtree_400Regular',
  },
  hoursScrollContainer: {
    flex: 1,
    paddingHorizontal: 16,
    minHeight: 400,
  },
  // Business Pictures Styles
  businessPicturesContainer: {
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  businessPicturesTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#222',
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: 'Figtree_600SemiBold',
  },
  businessPicturesSubtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 24,
    textAlign: 'center',
    fontFamily: 'Figtree_400Regular',
  },
  businessPicturesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 16,
    width: '100%',
  },
  businessPictureItem: {
    position: 'relative',
    width: '30%',
    height: 100,
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 8,
  },
  businessPicture: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  removeBusinessPictureButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 2,
  },
  addBusinessPictureButton: {
    width: '30%',
    height: 100,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#FB7A20',
    borderStyle: 'dashed',
    backgroundColor: '#f9f9f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  addBusinessPictureText: {
    color: '#FB7A20',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 4,
    fontFamily: 'Figtree_500Medium',
  },
  businessPicturesNote: {
    color: '#666',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  priceDisplayContainer: {
    backgroundColor: '#FFF5F0',
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#FB7A20',
    alignItems: 'center',
  },
  priceDisplayText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  priceAmount: {
    color: '#FB7A20',
    fontSize: 18,
    fontWeight: '700',
  },
  pricingInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  pricingInput: {
    flex: 1,
    marginRight: 8,
  },
  priceLevelBox: {
    backgroundColor: '#FB7A20',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    minWidth: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceLevelText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  imageRequirementsNote: {
    backgroundColor: '#FFF5F0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#FB7A20',
  },
  imageRequirementsText: {
    color: '#333',
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
    textAlign: 'center',
  },
  profilePictureCircle: {
    width: 116,
    height: 116,
    borderRadius: 58,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
}); 